name: Process IPs

on:
  workflow_dispatch:

jobs:
  process-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download txt.zip
      run: curl -L -o txt.zip https://zip.baipiao.eu.org/

    - name: Unzip txt.zip
      run: unzip txt.zip -d txt_files

    - name: Process IP files
      run: |
          mkdir -p output
          touch output/ip.txt
          for file in txt_files/*.txt; do
            port=$(basename "$file" | sed -E 's/.*-(.*)-.*/\1/')
            if [ "$port" -eq 443 ]; then
              while IFS= read -r ip; do
                echo "$ip:$port" >> output/ip.txt
              done < "$file"
            fi
          done
          cat output/ip.txt

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add output/ip.txt
        git commit -m "Processed and merged IPs"
        git push
